{% set name = "PyNaCl" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: cb36deafe6e2bce3b286e5d1f3e1c246e0ccdb8808ddb4550bb2792f2df298f2

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - gnuconfig  # [unix]
  host:
    - pip
    - python
    - setuptools >=61.0.0,!=74.0.0
    - cffi >=1.4.1
    - libsodium 1.0.20
    - msinttypes  # [win and vc<14]
  run:
    - python
    - six
    - cffi >=1.4.1
    - libsodium

test:
  source_files:
    - tests/
  imports:
    - nacl
    - nacl.pwhash
    - nacl.bindings
  requires:
    - pip
    - pytest >=7.4.0
    - hypothesis >=3.27.0
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/pyca/pynacl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PyNaCl is a Python binding to the Networking and Cryptography library.
  description: |
    PyNaCl is a Python binding to the Networking and Cryptography library,
    a crypto library with the stated goal of improving usability, security
    and speed. It supports Python 2.7 and 3.3+ as well as PyPy 2.6+.
  doc_url: https://pynacl.readthedocs.io
  dev_url: https://github.com/pyca/pynacl

extra:
  recipe-maintainers:
    - CJ-Wright
