{% set name = "PyNaCl" %}
{% set version = "1.2.0" %}
{% set sha256 = "45c5bcdf8ddefe2e9381f5d37fe778bbda6991fe7004e0b1ea3570df2fc07207" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - python
    - setuptools
    - cffi >=1.4.1
    - libsodium  # [win]

  build:
    - {{ compiler('c') }}

  run:
    - python
    - six
    - cffi >=1.4.1

test:
  imports:
    - nacl
    - nacl.bindings
    - nacl.pwhash
  requires:
    - pytest >=3.2.1
    - hypothesis >=3.27.0
  source_files:
    - tests/
  commands:
    - pytest

about:
  home: https://github.com/pyca/pynacl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PyNaCl is a Python binding to the Networking and Cryptography library, a crypto library with the stated goal of improving usability, security and speed.
  description: |
    PyNaCl is a Python binding to the Networking and Cryptography library, a crypto library with the stated goal of improving usability, security and speed. It supports Python 2.7 and 3.3+ as well as PyPy 2.6+.
  doc_url: https://pynacl.readthedocs.io/en/latest/
  dev_url: https://github.com/pyca/pynacl

extra:
  recipe-maintainers:
    - CJ-Wright
